### ISSUE TITLE
SKiDL and its dependence on symbols

### ISSUE THREAD

**Issue by wojtekbe** [xesscorp/skidl#18]
Since SKiDL is a netlist generator without involving any schematics, why it depends on symbols? It seems more reliable to make connections direclty to the pins of the footprint. It is very annoying to search through kicad's library for an existing symbol or creating a new symbol, which is not actually necesary for generating the netlist. I know I can create a SKiDL symbol library but still...

Of course I realize that I'll lose information about the pin type (input, output etc.) and as a result - ERC checking.

IMO a good start is to provide a feature of creating a Part() without passing the part's library name, and then ERC will warn user that this part has no pin information and it cannot be checked.

**Comment by xesscorp** [comment]
Symbol libraries contain drawing primitives (which SKiDL ignores) and part information including descriptions of all the pins (which SKiDL uses). SKiDL uses symbol libraries because that's where all the valuable information currently resides. SKiDL also supports its own library format that only stores part attributes and pin descriptions (and no drawing primitives).

It's might be possible to just make connections to the pins of a footprint, but there are many types of parts that uses the same footprint (e.g., resistors, capacitors, and inductors can all use the same 0805, 0603 and 0402 footprints). So it gets confusing to just have a bunch of pin number connections to nets without any association to actual parts. And ERC won't work without the extra information about pin types. There are some people who have tried the method you describe and their boards eventually reach a complexity where they come back from fabrication with errors and don't work. Then they start adding rules to catch the errors they made until they eventually end up reimplmenting ... part symbols!

In addition, there are parts that come in several types of packages where the pin names are mapped to different pin numbers on each package. By connecting directly to the pin numbers of packages, it becomes difficult to switch the package if the design changes. I showed an example of this [here](https://xesscorp.github.io/skidl/docs/_site/blog/names-not-numbers).
