### ISSUE TITLE
skidl.libs.* not accessible or searchable

### ISSUE THREAD

**Issue by donquichotte** [xesscorp/skidl#20]
I can't get SKiDL to search skdil.libs. 

I'm quite sure adding a `Part` with the lines below worked at some point, but can't seem to reproduce it!
 
```
In [1]:  from skidl import *
In [2]:  AD620 = Part(libs.linear_sklib.linear, 'AD620')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-18dcc70e8600> in <module>()
----> 1 AD620 = Part(libs.linear_sklib, 'AD620')

AttributeError: 'module' object has no attribute 'linear_sklib'
```

Also, `search` does not search the `libs` folder.

I'm using version 0.12, installed via pip.

**Comment by xesscorp** [comment]
I don't think using something like `libs.linear_sklib.linear` ever worked. At least, it doesn't work now. The library argument to `Part` has to be a string. If you had a library called `linear_sklib` under the skidl/libs directory, then you could get at it using `Part('linear_sklib.py', ...)` or `Part('linear', ...)` (which will add the `_sklib.py` suffix).

If you want to use the SKiDL libraries instead of the KiCad libraries, then you can use `set_default_tool(SKIDL)` to make SKiDL the default library format. Or else use `tool=SKIDL` in your calls to `Part()` and `search()` like so:

    search('resistor', tool=SKIDL)

Let me know if these work for you.
