### ISSUE TITLE
PySpice optional

### ISSUE THREAD

**Issue by jamesbowman** [xesscorp/skidl#36]
Am using Python2, but wanted to check Python 3. I see that PySpice is not optional for running SKiDL under Python3.

PySpice is **big**! The thing took 20 minutes to (fail to) install on my Ubuntu machine.

Since a minority of users will use PySpice, and it's quite big and (dare I say it) perhaps slightly brittle, it would be nice if it were optional.

Maybe friendlier if the PySpice import only happened if the PySpice function is called?

**Comment by xesscorp** [comment]
Hi, James. PySpice isn't that big, but it seems to load things like numpy which are big. I didn't see that before because most Python installs already have these things installed. Sorry about that.

Your immediate fix is to install a previous version before PySpice was used. Try this:

    pip install skidl==0.0.17

That will have all the current SKiDL features *except* PySpice.
